version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-apexsolar}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-apexsolar123}
      POSTGRES_DB: ${DB_NAME:-apexsolar}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-apexsolar}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - apexsolar-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER:-apexsolar}:${DB_PASSWORD:-apexsolar123}@postgres:5432/${DB_NAME:-apexsolar}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-here}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your-nextauth-secret-here}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NODE_ENV: production
      UPLOAD_DIR: uploads
      MAX_FILE_SIZE: 5242880
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@apexsolar.net}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - apexsolar-network

volumes:
  postgres_data:

networks:
  apexsolar-network:
    driver: bridge
