version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: apexsolar
      POSTGRES_PASSWORD: apexsolar123
      POSTGRES_DB: apexsolar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apexsolar"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://apexsolar:apexsolar123@postgres:5432/apexsolar
      JWT_SECRET: your-super-secret-jwt-key-here
      NEXTAUTH_SECRET: your-nextauth-secret-here
      NEXTAUTH_URL: http://localhost:3000
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
