name: Comprehensive Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

env:
  NODE_VERSION: '18'

jobs:
  # Authentication Tests
  auth-tests:
    name: Authentication Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Make test scripts executable
      run: chmod +x ./tests/*.sh
    
    - name: Run Authentication Tests
      run: ./tests/test-auth-fixes.sh
      env:
        BASE_URL: ${{ secrets.STAGING_URL || 'https://apexsolar-staging-302444603160.asia-south1.run.app' }}

  # Comprehensive System Tests
  system-tests:
    name: System Integration Tests
    runs-on: ubuntu-latest
    # Only run comprehensive tests on develop branch where staging exists
    if: github.ref == 'refs/heads/develop' || github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Make test scripts executable
      run: chmod +x ./tests/*.sh
    
    - name: Run Comprehensive Tests
      run: ./tests/comprehensive-test-suite.sh
      env:
        BASE_URL: ${{ secrets.STAGING_URL || 'https://apexsolar-staging-302444603160.asia-south1.run.app' }}
    
    - name: Cleanup Test Data
      if: always()
      run: |
        echo "🧹 Cleaning up test data created during testing..."
        # The test suite creates test data with timestamp patterns - clean it up
        ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}" ./production-cleanup.sh || echo "Cleanup script not available"
      env:
        PROD_BASE_URL: ${{ secrets.STAGING_URL || 'https://apexsolar-staging-302444603160.asia-south1.run.app' }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: comprehensive-test-results
        path: |
          test-results.json
          test-report.html

  # Security Tests
  security-tests:
    name: Security Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Make test scripts executable
      run: chmod +x ./tests/*.sh
    
    - name: Run Security Tests
      run: ./tests/security-test-suite.sh
      env:
        BASE_URL: ${{ secrets.STAGING_URL || 'https://apexsolar-staging-302444603160.asia-south1.run.app' }}
    
    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-test-results
        path: |
          security-report.json
          security-summary.md

  # Performance Tests
  performance-tests:
    name: Performance & Load Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Make test scripts executable
      run: chmod +x ./tests/*.sh
    
    - name: Run Performance Tests
      run: ./tests/performance-test-suite.sh
      env:
        BASE_URL: ${{ secrets.STAGING_URL || 'https://apexsolar-staging-302444603160.asia-south1.run.app' }}
    
    - name: Upload performance report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-test-results
        path: |
          performance-report.json
          load-test-results.html

  # Test Summary
  test-summary:
    name: Generate Test Summary
    runs-on: ubuntu-latest
    needs: [auth-tests, security-tests, performance-tests]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Make test scripts executable
      run: chmod +x ./tests/*.sh
    
    - name: Generate Test Summary
      run: ./tests/test-summary.sh
      env:
        BASE_URL: ${{ secrets.STAGING_URL || 'https://apexsolar-staging-302444603160.asia-south1.run.app' }}
    
    - name: Upload test summary
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-summary-report
        path: |
          test-summary.md
          test-overview.json
    
    - name: Comment Test Results on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('test-summary.md')) {
            const summary = fs.readFileSync('test-summary.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## 🧪 Test Results\n\n' + summary
            });
          }

  # Notification on Failure
  notify-failure:
    name: Notify on Test Failure
    runs-on: ubuntu-latest
    needs: [auth-tests, security-tests, performance-tests]
    if: failure()
    
    steps:
    - name: Notify Team
      run: |
        echo "❌ Tests failed in workflow: ${{ github.workflow }}"
        echo "🔗 View details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        # Add your notification logic here (Slack, email, etc.)

  # Post-test staging cleanup
  staging-cleanup:
    name: Clean Staging Environment
    runs-on: ubuntu-latest
    needs: [auth-tests, security-tests, performance-tests]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup cleanup environment
      run: |
        chmod +x ./production-cleanup.sh
        echo "🧹 Preparing to clean staging environment after tests"
    
    - name: Run staging cleanup
      env:
        # Use staging URL for cleanup, never production
        BASE_URL: ${{ secrets.STAGING_URL || 'https://apexsolar-staging-302444603160.asia-south1.run.app' }}
        CI_MODE: true
        ADMIN_PASSWORD: ${{ secrets.STAGING_ADMIN_PASSWORD }}
      run: |
        echo "Running cleanup on staging environment: $BASE_URL"
        echo "🔒 CI Mode enabled - automated cleanup without prompts"
        ./production-cleanup.sh || echo "⚠️ Cleanup completed with warnings"
    
    - name: Cleanup summary
      run: |
        echo "✅ Staging environment cleanup completed"
        echo "🎯 Test data removed from staging to prevent accumulation"

  # Local System Tests (for main branch)
  local-tests:
    name: Local Integration Tests
    runs-on: ubuntu-latest
    # Only run on main branch since staging doesn't exist there
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: apexsolar_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Generate Prisma client
      run: npm run db:generate
    
    - name: Setup test database
      run: npm run db:push
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/apexsolar_test
    
    - name: Seed test database
      run: npm run db:seed
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/apexsolar_test
    
    - name: Build application for testing
      run: npm run build
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/apexsolar_test
        JWT_SECRET: test-jwt-secret-for-github-actions
        NEXTAUTH_SECRET: test-nextauth-secret-for-github-actions
        NEXTAUTH_URL: http://localhost:3000
        NODE_ENV: test
    
    - name: Start test server in background
      run: |
        npm start &
        echo $! > server.pid
        sleep 15
        curl --retry 10 --retry-delay 3 --retry-connrefused http://localhost:3000/api/health || echo "Server startup check failed"
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/apexsolar_test
        JWT_SECRET: test-jwt-secret-for-github-actions
        NEXTAUTH_SECRET: test-nextauth-secret-for-github-actions
        NEXTAUTH_URL: http://localhost:3000
        NODE_ENV: test
        PORT: 3000
    
    - name: Make test scripts executable
      run: chmod +x ./tests/*.sh
    
    - name: Run comprehensive tests on localhost
      run: ./tests/comprehensive-test-suite.sh
      env:
        BASE_URL: http://localhost:3000
    
    - name: Stop test server
      run: |
        if [ -f server.pid ]; then
          kill $(cat server.pid) || echo "Server already stopped"
          rm server.pid
        fi
      if: always()
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: local-test-results
        path: |
          test-results.json
          test-report.html
